### ISSUE TITLE
Infinite Line Effector starts animation at end value

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#190]
# Bug Report

# Environement
- Duik 16.0.1-Alpha-9

### After Effects
- CC2018 (15.1.1)
- English

### OS
- Mac OS 10.13.4

# What's the issue?
When applying the infinite line effector, the animation starts with the end value of the objects instead of their initial value. One could click the inverse checkbox but the logical behaviour would be having the elements starting with their initial values.

# Request
I think it would also be good that if the Effector was deleted, all the effects on the layers and the expressions should be removed as well.

Thanks, René

**Comment by Nico-Duduf** [comment]
Thanks, the bug is fixed.

As for the suggestion, it's not possible to "listen" for layer deletion with a script, so unfortunately it won't be possible to automatically remove effects and expressions when the Effector is removed.

We can imagine, in a future version of Duik, to add a 'remove' button somewhere to help remove effects/expressions created with Duik. I'm thinking about that, it's quite complex to do, but I'd like to find a way to do this.
