### ISSUE TITLE
clamp the connector's controller?

### ISSUE THREAD

**Issue by Tim1022** [Rainbox-dev/DuAEF_Duik#267]
# Feature Request

It would be great if we could make the connector's controller being clamped in the slider.

### Tool

- Duik

### Steps

1. When sliding the controller, it isn't clamped into the slide.

### Expected behaviour
I'm not very good at coding, but I thought an idea to clamp the controller.  Eg, if it's a slider connector, we can apply the codes below to the controller's position property:

`sHandle=thisComp.layer("CBG | Dark Purple Solid").content("Anchor").content("Rectangle Path 1").size[0];`

`cRadius = thisLayer("Contents")("Icon")("Contents")("Ellipse Path 1")("Size")[0]/2;`

`cPosition = thisLayer("Transform")("Position")[0];`

`[clamp(cPosition,sHandle/2*-1+cRadius,sHandle/2-cRadius),0];`

**Comment by Nico-Duduf** [comment]
Hi,

We've chosen not to clamp the position, as it does not prevent the user to actually set a value outside of the bounds (this happens when you move the controller away, it will visually stay on the bound, but the value will actually go further)

This is an isse when you try to move again the controller later, which won't move until you get back inside the bounds, and you could think something is broken.
This happened a lot during the beta tests, and can not be work around, as it's how expressions work.

Maybe we could add an option for user who would like to clamp the values anyway?
