### ISSUE TITLE
Add bones issues

### ISSUE THREAD

**Issue by petrholusa** [Rainbox-dev/DuAEF_Duik#638]
**Describe the bug**
After adding 3 legacy puppets pins into the graphics after clicking Add Bones nothing happen, just one pin. No magic screen. Worked only manually by selecting each pin and from detail panel of Add Bones clicking Create.

**To Reproduce**
1. Add puppet pins to graphic layer (curves)
2. Changed to legacy
3. Select layer with puppets pins
4. Click Add Bones in DUIK panel

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 17.0.2
 - Version of Duik: .16.2.6

Thank you kindly for this plugin. :)

**Comment by Nico-Duduf** [comment]
In the latest versions of Duik, it won't add bones on the pins if it's only the layer which is selected. You have to select either the puppet effect or each pin.
This is because the bones in Duik Bassel can be created also on any spatial property or bézier path, so selected the layer is not enough to tell Duik which property you want to add bones to.

**Comment by petrholusa** [comment]
I see. Thank you very much to clarify...

Petr Holuša / Freelance Graphic Designer
info@petrholusa.com / +420 705 104 320
www.petrholusa.com
