### ISSUE TITLE
Extracting controller via master properties does not work for 2D Sliders/Sliders/angle

### ISSUE THREAD

**Issue by AdrianHilmmer** [Rainbox-dev/DuAEF_Duik#641]
**Describe the bug**
Extracting the character rig via master properties does not work. Duik extracts all controllers, but only creates master properties for a "joystick". Using expressions does work. 

**To Reproduce**
1. use extract (in the options set to master properties)
2. wait
3. sad cause handles are created, but just master properties for the head joystick

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
extracted controller with master properties that do work ^^

**Screenshots**
Think this is clear

**System (please complete the following information):**
 - OS: win 10
 - Version of After Effects: 17.0.2
 - Version of Duik: 16.2.6

**Additional context**

[character_template_MP_extract_bug.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/4169786/character_template_MP_extract_bug.zip)

**Comment by Nico-Duduf** [comment]
There was an issue due to the folder already existing in the master properties,

But I've found another issue due to a bug in After Effects. It seems we need to trigger the "pull" button of the master properties after creation to make them work with the zeroes of Duik (with the parenting between comps).

Still working on it.

In the meantime, you can:
- avoid folders in master properties
- try to not use zeroes

**Comment by Nico-Duduf** [comment]
Needs to be tested in  another new/clean project

**Comment by ronruizG** [comment]
Hi! I don't know how much this can slow down things but maybe Zeroes for a controller could be applied via expression and not parenting? This way the output of the expression could be the default position of the controller but the "value input" for keyframe creation would be zeroed (I think I made out that word, don't know :P), because the cool thing about zeroed values is that you can input zeros as value and expect the default position. We could add this zero expression to the MP controllers after the extraction.

**Comment by AdrianHilmmer** [comment]
Thanks for investigating into this :)

**Comment by Nico-Duduf** [comment]
@ronruizG The problem is that the "zero" tool is also used a lot to simplify expression writing, as it makes it easy to link properties which have been zeroed out.
Making this with expressions is also going to be an issue when parenting layers, it makes it a bit more complext (having to remove all the transform expressions before parenting, to re-use the "zero" tool after)

**Comment by Nico-Duduf** [comment]
Good news, issue fixed!

I'll release 16.2.7 ASAP, everything is ready I just need some time to build and upload the file, should be done this week

**Comment by AdrianHilmmer** [comment]
@Nico-Duduf that sounds great!
