### ISSUE TITLE
Auto-rig Problem

### ISSUE THREAD

**Issue by longertom1990** [Rainbox-dev/DuAEF_Duik#650]
**Describe the bug**
Auto-rig in all Duik Bassel 2 (all versions for me) makes strange behaviour of rigged Spine Structure:
 
By changing the position of Head Controler, Head Structure is disconnecting from Neck Structure and is moving along with Head Controler. 
As well by changing the position of Shoulders & Neck Controler, Head Structure is disconnecting from Neck Structure and is moving along with Shoulders & Neck Controler (together with Head Controler). During this movement, Spine | Curve Controler is not moving at all. The problem is seen mainly during the change of Y value position of Shoulders & Neck Controler.
Other issues - when I'm changing the position of Toes Controler, Heels and Tiptoes Structures are not moving along with parented Structures, they are still.
Spine and Spine 2 Structures are also moving in a strange way but it's hard to describe.

Problem was solved when I deselected Bake Structures in Auto-rig & IK and then used it. 

**To Reproduce**
1. Add Spine Structure.
2. Select Structure.
3. Press Autorig.

**Error description, if any**

**Expected behavior**
The spine should be rigged correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/61454125/75237331-7619e500-57bf-11ea-8056-dc0b96a38e69.png)
![image](https://user-images.githubusercontent.com/61454125/75237389-8c27a580-57bf-11ea-99e4-7dd31821c725.png)

**System (please complete the following information):**
 - OS: Windows 10 Home
 - Version of After Effects: 17.0.1
 - Version of Duik: all versions of 16.2

**Additional context**
Also Duik Bassel 16.1 works fine.

**Comment by Nico-Duduf** [comment]
The head controler moves like this by design. If you need to rotate the neck, you have to use the rotation of the "Shoulders and Neck" controller.

The Spine Curve controller is not meant to move automatically, it has to be animated if needed.
For the movement of the Torso, parent some layers to the structures, you'll see it works as expected.

For the rest, just parent some design to the structures you'll see everything works as expected. When they're "baked" there may seem to be some issues which are just display issues, not actual rigging issues, this is perfectly normal and improves performance.

For anyone reading this, please don't post bug reports before you have really used Duik enough to be sure you're actually facing bugs. At least, try to rig an actual character and not just do some testing with only structures. You can also **[read the doc](http://duik-docs.rainboxlab.org)**, please.

**Comment by longertom1990** [comment]
Hi Duduf,

Here is rigged character (with design as you suggested). It's still not working fine for me.
Changing the position of _Shoulders & Neck Controler_ makes _Head Structure_ disconnect from _Neck Structure_.
![Screenshot_3](https://user-images.githubusercontent.com/61454125/75357866-56afb480-58b2-11ea-99db-4767497be6ef.png)
A. First Spine is rigged with Bake option off
B. Second is with Bake option on
C. Second is with Bake option on and with parented design.

Maybe I'm wrong, but this isn't looking all fine, right?
Project folder if you are interested:
https://drive.google.com/file/d/1HScJB3pmIv-UVsJVmj-xkPI5c4ChWOyB/view?usp=sharing

**Comment by Nico-Duduf** [comment]
This makes my point: the design moves correctly, it's just the structures which are not properly displayed, which is just the goal of baking them.
