### ISSUE TITLE
Bug IK/FK when controller has been extracted with master properties

### ISSUE THREAD

**Issue by The-Chacal** [Rainbox-dev/DuAEF_Duik#694]
Problème avec le bouton "Passage IK/FK" du panel Animation, au retour à l'IK, le controleur ne se place pas au bon endroit.

**To Reproduce**
1. Rigger la marionnette en utilisant les zéros sur les contrôleurs
2. Extraire les controleurs de la puppet dont les dimensions ne sont pas les mêmes que la composition dans laquelle elle est utilisée
3. Basculer de IK à FK sans soucis, mais l'inverse n'est pas vrai.

**System (please complete the following information):**
 - OS: win 10
 - Version of After Effects: 17.1.1
 - Version of Duik: 16.2.13

**Comment by Nico-Duduf** [comment]
Hi,

Thanks for your feedback.

Did you extract using expressions or master properties?
From my testing here it seems the IK/FK tool works properly when the extraction was made using expressions but not master properties.

It's going to be a bit complex to fix, as the data for the switch has to be taken from the precomp, which may be in a lot of different states due to master properties, so you'll have to wait a bit for the fix to be available, sorry.


Note for myself: to fix, adjust the values inside the precomp from the values of the extracted controller, switch the IK or FK and then restore the previous values in the precomp.

**Comment by The-Chacal** [comment]
I have extracted the controllers with expressions too.

Here's an aep where I can reproduce the bug.

Le dim. 21 juin 2020 à 18:31, Nicolas Dufresne <notifications@github.com> a
écrit :

**Comment by The-Chacal** [comment]
The bug comes from the fact that the position of the controller is set
according to the top left corner of the current comp, not from the top left
corner of the comp from which I extracted the controller. I tried to make
those corner match, then the IK/FK button works again.

Le lun. 22 juin 2020 à 09:18, Sylvain Lorent <sylvainlorent@gmail.com> a
écrit :

**Comment by Nico-Duduf** [comment]
Oh I understand, that's another issue.
Thanks for the feedback, this one will be an esay fix, I'll add it in the next update ASAP

**Comment by Nico-Duduf** [comment]
I've created issue #696 for the transformation issu

**Comment by Nico-Duduf** [comment]
fixed
