### ISSUE TITLE
Function in controller

### ISSUE THREAD

**Issue by Kamsus** [Rainbox-dev/DuAEF_Duik#756]
Hello dear Duduf!

Big request! Please do it in the next version!
Stretch in the controller is DEFAULT OFF.
This is logical. In human life, hands and feet are not separate.
And saving time. No need to press the button again.

From Russia with love.
Best Regards for you and yours!

![duduf](https://user-images.githubusercontent.com/71124997/97101436-f8043a00-16cf-11eb-9a68-1a81ada8a411.jpg)

**Comment by Nico-Duduf** [comment]
Hi Kamsus,

I won't do that for two resons:

- 99% of the time, animators won't see any difference: if the animator does not want to stretch, it's his/her choice to not pull on the controller. With or without stretch, the limb should mot be pulled anyway. And if it's pulled, that means you need stretch.

- you can use Animation presets in Ae to have your own values. You can activate the list of presets right in the effects panel, so that you can select any preset very quickly, without even using the list from the Presets panel, but right from the effect itself.
