### ISSUE TITLE
REPORT BUG FROM DUIK BASSEL 2 ON AFTER EFFECT CC 2018

### ISSUE THREAD

**Issue by giatcaminh92** [Rainbox-dev/DuAEF_Duik#822]
**Describe the bug**
When I change DUIK BAssel 2 To Expert Mode. It's lag when i choose Rigging -  Links and constrains

**Screenshots**
![image](https://user-images.githubusercontent.com/81545097/112783153-dd682f80-9078-11eb-8471-4ad38eb140b8.png)

**System (please complete the following information):**
 - OS: WINDOWS 10
 - Version of After Effects: CC 2018
 - Version of Duik: Duik Bassel 2

**Additional context**
Please Fix it !

**Comment by Nico-Duduf** [comment]
I can't reproduce the issue here on After Effects 2020.

Also, you can follow this "fix & uninstall" procedure as described there: https://duik-docs.rainboxlab.org/install-duik.html#fix-uninstall-duik
this may fix the issue.

Can you try with a more recent version of After Effects and let me know if you still have the issue?

**Comment by giatcaminh92** [comment]
It works good on AE 2019. I think 2020 too.
